# Generated by Django 2.0.3 on 2018-03-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='led13',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='sensors1',
            field=models.FloatField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='sensors2',
            field=models.FloatField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='temperature',
            field=models.FloatField(default=True),
        ),
    ]
